

### Login to get token
POST https://sika-tree-survey-backend-production.up.railway.app/api/v1/auth/login/
Accept: application/json
Content-Type: multipart/form-data; boundary=LoginBoundary

--LoginBoundary
Content-Disposition: form-data; name="email"

admin@example.com

--LoginBoundary
Content-Disposition: form-data; name="password"

Admin@123

--LoginBoundary--

> {%
     client.global.set("access_token", response.body.data.tokens.access);
%}

### Get user profile with stored token
GET https://sika-tree-survey-backend-production.up.railway.app/api/v1/users/profile/me/
Accept: application/json
Authorization: Bearer {{access_token}}

> {%
    client.test("Profile retrieved successfully", function() {
        client.assert(response.status === 200);
        client.assert(response.body.email === "admin@example.com");
    });
%}


### Get user profile with stored token
GET https://sika-tree-survey-backend-production.up.railway.app/api/v1/dashboard/project_dashboard/?project_id=fffc9a01-dc99-426b-ab7d-ce24e2507569
Accept: application/json
Authorization: Bearer {{access_token}}

> {%
    client.test("Project Dashboard retrieved successfully", function() {
        client.assert(response.status === 200);
        client.assert(response.body.email === "admin@example.com");
    });
%}

